FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci --only=production
RUN npx prisma generate

COPY . .

# Dar permisos de ejecución al script
RUN chmod +x start.sh

EXPOSE 3000

# Usar el script de inicio
CMD ["./start.sh"]